"""add sort_order to bank_accounts

Revision ID: 23763ee0330f
Revises: 77754f53d5d5
Create Date: 2026-09-10 22:19:41.240051

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '23763ee0330f'
down_revision: str | Sequence[str] | None = '77754f53d5d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'sort_order')
    # ### end Alembic commands ###
