"""add display_name to bank_accounts

Revision ID: 77754f53d5d5
Revises: 005c46b0dd2f
Create Date: 2026-09-10 22:03:27.417335

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '77754f53d5d5'
down_revision: str | Sequence[str] | None = '005c46b0dd2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'display_name')
    # ### end Alembic commands ###
