"""add balance cache columns to bank_accounts

Revision ID: cf2ca903c279
Revises: 44058e190be7
Create Date: 2026-09-10 20:11:09.296961

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cf2ca903c279'
down_revision: str | Sequence[str] | None = '44058e190be7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('current_balance', sa.Numeric(), nullable=True))
    op.add_column('bank_accounts', sa.Column('available_balance', sa.Numeric(), nullable=True))
    op.add_column('bank_accounts', sa.Column('balance_currency', sa.String(), nullable=True))
    op.add_column('bank_accounts', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bank_accounts', sa.Column('sync_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'sync_status')
    op.drop_column('bank_accounts', 'last_synced_at')
    op.drop_column('bank_accounts', 'balance_currency')
    op.drop_column('bank_accounts', 'available_balance')
    op.drop_column('bank_accounts', 'current_balance')
    # ### end Alembic commands ###
