"""add users, banks, bank_accounts, transactions

Revision ID: dac33a64113b
Revises: a01a452e9a79
Create Date: 2026-09-02 18:28:13.803413

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dac33a64113b'
down_revision: str | Sequence[str] | None = 'a01a452e9a79'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: reordered so
    # bank_connections is fully migrated to its new shape (including a new
    # primary key on connection_id) before bank_accounts/transactions are
    # created referencing it. ###
    op.create_table('banks',
    sa.Column('bank_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bank_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )

    op.add_column('bank_connections', sa.Column('connection_id', sa.Uuid(), nullable=False))
    op.add_column('bank_connections', sa.Column('bank_id', sa.Uuid(), nullable=False))
    op.alter_column('bank_connections', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               postgresql_using='user_id::uuid',
               existing_nullable=False)
    op.drop_index(op.f('ix_bank_connections_user_id'), table_name='bank_connections')
    op.drop_column('bank_connections', 'aspsp')
    op.drop_column('bank_connections', 'account_ids')
    op.drop_column('bank_connections', 'id')
    op.create_primary_key('bank_connections_pkey', 'bank_connections', ['connection_id'])
    op.create_foreign_key(None, 'bank_connections', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'bank_connections', 'banks', ['bank_id'], ['bank_id'])

    op.create_table('bank_accounts',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('cash_account_type', sa.String(), nullable=True),
    sa.Column('bic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['bank_connections.connection_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('credit_debit_indicator', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('remittance_information', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_connections', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('bank_connections', sa.Column('account_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('bank_connections', sa.Column('aspsp', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bank_connections', type_='foreignkey')
    op.drop_constraint(None, 'bank_connections', type_='foreignkey')
    op.create_index(op.f('ix_bank_connections_user_id'), 'bank_connections', ['user_id'], unique=False)
    op.alter_column('bank_connections', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('bank_connections', 'bank_id')
    op.drop_column('bank_connections', 'connection_id')
    op.drop_table('transactions')
    op.drop_table('bank_accounts')
    op.drop_table('users')
    op.drop_table('banks')
    # ### end Alembic commands ###
